<?php
/* Smarty version 3.1.33-p1, created on 2019-07-09 12:57:43
  from 'mailMessage:message' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '3.1.33-p1',
  'unifunc' => 'content_5d247327c11432_33241994',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '652e3de8ff57f412acf7c0a8dadc70dc1a7637b6' => 
    array (
      0 => 'mailMessage:message',
      1 => 1562669863,
      2 => 'mailMessage',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_5d247327c11432_33241994 (Smarty_Internal_Template $_smarty_tpl) {
$template = $_smarty_tpl;
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>Réinitialisation du mot de passe </title>
        <style type="text/css">
            [EmailCSS]
        </style>
    </head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
        <center>
            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">
                <tr>
                    <td align="center" valign="top" id="bodyCell">
                        <table border="0" cellpadding="0" cellspacing="0" id="templateContainer">
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader">
                                        <tr>
                                            <td valign="top" class="headerContent">
                                                <img src="" style="max-width:600px;padding:20px 20px 0 20px" id="headerImage" alt="Triplehost LLC" />
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody">
                                        <tr>
                                            <td valign="top" class="bodyContent">
                                                <p>Bonjour <?php echo $_smarty_tpl->tpl_vars['firstname']->value;?>
,<br /><br />Récemment, une demande a été soumise pour réinitialiser votre mot de passe administrateur. Suivez le lien ci-dessous pour le réinitialiser.</p>
<p><a href="<?php echo $_smarty_tpl->tpl_vars['pw_reset_url']->value;?>
"><?php echo $_smarty_tpl->tpl_vars['pw_reset_url']->value;?>
<br /><br /><br /></a>Si vous n'avez pas demandé de réinitialisation d'un mot de passe, ignorez ce courriel. Le lien du mot de passe expirera en 2 heures.</p>
<div><span lang="fr"> </span></div>
<p><?php echo $_smarty_tpl->tpl_vars['whmcs_admin_link']->value;?>
</p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateFooter">
                                        <tr>
                                            <td valign="top" class="footerContent">
                                                <a href="https://www.whmcs.com/"><img src="https://cdn.whmcs.com/images/whmcs_email_footer.png" id="footerImage" alt="WHMCS" /></a>
                                                This notification was automatically generated by WHMCS<br />
                                                &nbsp;<a href="http://www.triplehost.net/">http://www.triplehost.net/</a>
                                                <span class="hide-mobile"> | </span>
                                                <a href="http://www.triplehost.net/admin_DgHfV3KAf2uwPEtYKgokpfMTH/">log in to the admin area</a>&nbsp;
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html><?php }
}
